Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -37,27 +37,13 @@ jobs:
           scheme: ${{ 'default' }}
           platform: ${{ 'iOS Simulator' }}
         run: |
-          device=$(xcrun xctrace list devices 2>&1 \
-            | grep -oE 'iPhone.*?[^\(]+' \
-            | head -1 \
-            | awk '{$1=$1;print}' \
-            | sed -e "s/ Simulator$//")
-          if [ "$scheme" = "default" ]; then 
-            scheme=$(cat default)
-          fi
+          device=$(xcrun simctl list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1)
+          echo "Selected device: $device"
+          if [ -z "$device" ]; then echo "Error: No device found."; exit 1; fi
+          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
           workspace_file=$(ls -A | grep -i '\.xcworkspace$')
-          if [ -n "$workspace_file" ]; then 
-            filetype_parameter="workspace"
-            file_to_build="$workspace_file"
-          else 
-            project_file=$(ls -A | grep -i '\.xcodeproj$')
-            filetype_parameter="project"
-            file_to_build="$project_file"
-          fi
-          xcodebuild build-for-testing \
-            -scheme "$scheme" \
-            -"$filetype_parameter" "$file_to_build" \
-            -destination "platform=$platform,name=$device"
+          if [ -n "$workspace_file" ]; then filetype_parameter="workspace"; file_to_build="$workspace_file"; else project_file=$(ls -A | grep -i '\.xcodeproj$'); filetype_parameter="project"; file_to_build="$project_file"; fi
+          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
 
       - name: Run Unit Tests
         run: |
